blank_issues_enabled: false
contact_links:
  - name: Get the app / check for updates
    url: https://f-droid.org/packages/com.yosefario.nclientv3/
    about: Download the latest version or check for updates on F-Droid.
